services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    container_name: rabbitmq
    restart: always
    networks:
      - rss_network
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres:14.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    networks:
      - main
    ports:
      - 5432:5432

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    container_name: redis
    networks:
      - main
    ports:
      - 6380:6379

  app:
    build: .
    volumes:
      - .:/app
    container_name: rss_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    networks:
      - main
    ports:
      - 8000:8000

  celery:
    build: .
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT="True"
    container_name: celery
    command: "celery -A config worker -l INFO"
    depends_on:
      - db
      - redis
      - app
    restart: always
    networks:
      - main

  celery_beat:
    build: .
    volumes:
      - .:/app
    container_name: celery_beat
    command: "celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - redis
      - app
    restart: always
    networks:
      - rss_network

  register_consumer:
    build: .
    container_name: register_consumer
    command: "python manage.py runconsumer register"
    depends_on:
      - rabbitmq
      - app
    restart: always
    networks:
      - rss_network

  login_consumer:
    build: .
    container_name: login_consumer
    command: "python manage.py runconsumer login"
    depends_on:
      - rabbitmq
      - app
    restart: always
    networks:
      - rss_network


networks:
  main:

volumes:
  postgres_data:
  redis_data: