services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_DB=rss
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zmahjour@1375
    networks:
      - main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis

  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_app
    volumes:
      - .:/src/rss
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - main

  celery:
    container_name: celery
    command: "celery -A config.celery worker -l INFO"
    depends_on:
      - db
      - app
      - redis
    image: app-image
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data: