# Generated by Django 4.2.5 on 2023-11-01 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0002_alter_comment_user_notification"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorite",
            new_name="Like",
        ),
        migrations.RenameIndex(
            model_name="like",
            new_name="interaction_content_54abc9_idx",
            old_name="interaction_content_a8ff7f_idx",
        ),
    ]
