# Generated by Django 4.2.5 on 2023-10-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=25, null=True)),
                ("owner_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="podcasts.category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rss_url", models.URLField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.TextField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=10, null=True)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "episode_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("audio_url", models.URLField(max_length=500)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcasts.channel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="rss",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="podcasts.rss"
            ),
        ),
    ]
