# Generated by Django 4.2.5 on 2023-09-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="episode",
            name="audio_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="episode",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
